### PR TITLE
fix(scripts): dream.py typo

### PR DESCRIPTION
**Pull request by tildebyte**
Stumbled on this while playing with `blue`, and thought it looked like a typo.

Introduced in 239f41f https://github.com/lstein/stable-diffusion/blob/239f41f3e0027900ee73196ac89850a9d172c0e9/scripts/dream.py#L274

Signed-off-by: Ben Alkov <ben.alkov@gmail.com>

### CODE REVIEW

**Review by lstein — APPROVED** [review]
Absolutely. The typo breaks grid generation. I'm surprised nobody complained. Thanks for finding and fixing this.

**Comment by psychedelicious** [comment]
Grid is still not working with this fix:
```python
>>   3 image(s) generated in 27.66s
Traceback (most recent call last):
  File "/Users/spencer/Documents/Code/stable-diffusion/scripts/dream.py", line 355, in <module>
    main()
  File "/Users/spencer/Documents/Code/stable-diffusion/scripts/dream.py", line 95, in main
    main_loop(gen, opt, infile)
  File "/Users/spencer/Documents/Code/stable-diffusion/scripts/dream.py", line 272, in main_loop
    metadata = metadata_dumps(
TypeError: metadata_dumps() got an unexpected keyword argument 'weights'
```

Changing the call of `metadata_dumps()` here:
https://github.com/tildebyte/stable-diffusion/blob/c19a5fe08f24c7f20fb89c6c202fadf52d9f135f/scripts/dream.py#L272-L277

to this:
```python
opt.weights = gen.weights
metadata = metadata_dumps(
    opt,
    seeds      = grid_seeds,
    model_hash = gen.model_hash
    )
```
seems to work.
