### PR TITLE
fit the destination image size to the init image aspect ratio

### PR DESCRIPTION
**Pull request by lstein**
Users request that the aspect ratio of the init image should constrain the dimensions of the generated image, rather than the other way around. This implements this request in a way that does not increase the overall area (and VRAM requirements) of the generated image.

In addition, there was a bug in how the destination image's dimensions were calculated, and this fixes that.

### CODE REVIEW

**Comment by cvar66** [comment]
I tried your code and still having issues.  When I I use the webUI with a 512 X 704 image and enter those demensions in the field it resizes my image to 320 X 512.

loaded input image of size 512x704 from ./img2img-tmp.png
resized input image to size 320x512 (use -H to adjust)

At the command line I get this error

Traceback (most recent call last):
  File "scripts/dream.py", line 516, in <module>
    main()
  File "scripts/dream.py", line 95, in main
    main_loop(t2i, opt.outdir, opt.prompt_as_dir, cmd_parser, infile)
  File "scripts/dream.py", line 178, in main_loop
    normalized_prompt = PromptFormatter(t2i, opt).normalize_prompt()
  File "e:\stable-diffusion\ldm\dream\pngwriter.py", line 120, in normalize_prompt
    switches.append(f'-b{opt.batch_size   or t2i.batch_size}')
AttributeError: 'Namespace' object has no attribute 'batch_size'

**Comment by lstein** [comment]
You found two bugs. Thank you!
The web server version should be working now. Please test and let me know what you observe. I hope the behavior will be more intuitive now.

**Comment by cvar66** [comment]
I just updated with git and know I have a new problem. webUi loaded up fine, but as soon as i hit generate I get this error. 

 File "e:\stable-diffusion\ldm\dream\server.py", line 91, in do_POST
    pngwriter = PngWriter(
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given

**Comment by bakkot** [comment]
> webUi loaded up fine, but as soon as i hit generate I get this error

That's caused by https://github.com/lstein/stable-diffusion/commit/3be1cee17cd0801d3d7e18b8547400dad2729f94 having missed [this line](https://github.com/lstein/stable-diffusion/blob/2aa83932728242b05248fada8447506e2fbed9f0/ldm/dream/server.py#L92), and will be fixed by https://github.com/lstein/stable-diffusion/pull/231. In the mean time, you can delete the `, 1` from the linked line and it should work.

**Comment by cvar66** [comment]
I removed the  `, 1` and now I get this

 File "e:\stable-diffusion\ldm\dream\server.py", line 134, in do_POST
    step_writer = PngWriter('./outputs/intermediates/', prompt, 2)
TypeError: __init__() takes from 2 to 3 positional arguments but 4 were given

**Comment by lstein** [comment]
This PR does the same thing as @blessedcoolant 's PR #229. I'm testing his version now and will use that in preference to this one because he's added checks for more edge cases.

**Comment by lstein** [comment]
Abandoned.
